### ISSUE TITLE
Let's collaborate on a MA3 version of this plugin 🎉

### ISSUE THREAD

**Issue by lukas-runge** [locimation/ma2-tc-import#1]
Hey @locimation,

i just started working on a MA3 version of your TC Live tool here: https://github.com/gegenLichtLindenfels/liveConnect2Reaper
Just wanted to let you know in case you want to collaborate 😉✨

Kind regards
Lukas

**Comment by gdyr** [comment]
Hi Lukas,

I don't currently have plans to develop an MA3 version of these plugins, but feel free to get in touch if you get stuck on anything!

Cheers
Michael
